version: '3.3'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=transcendence
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
  app:
    container_name: app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro

