version: '3.3'

services:
  ################ Postgresql ################
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    networks:
      - webnet
  ################## Website #################
  website:
    container_name: website
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    build:
      context: .
      dockerfile: ./docker/production.Dockerfile
      args:
        NODE_ENV: production
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
  
volumes:
  pgdata:
    driver: local
