version: '3.3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
  app:
    restart: unless-stopped
    build: ./docker
    container_name: app
    volumes:
      - /etc/localtime:/etc/localtime:ro

