version: '3.3'

# TODO use .env

services:
  ################ Postgresql ################
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  ################# Transcendence #################
  transcendence:
    container_name: transcendence
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080 # env
    build:
      context: .
      dockerfile: ./docker/back.Dockerfile
      args:
        NODE_ENV: production
    volumes:
      - /etc/localtime:/etc/localtime:ro