version: '3.3'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5434:5432
